import type { Unit } from "./types"

// This function simulates fetching data from an API
export async function fetchUnitsData(): Promise<Unit[]> {
  // In a real application, this would be a fetch call to your API
  // return fetch('/api/units').then(res => res.json())

  // For demonstration purposes, we'll return mock data
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: "1",
          name: "DESCOMPLICAR BUTANTÃ",
          isMainUnit: true,
          totalServices: "259",
          services: 259,
          waitTime: "01:52:45",
          under30min: 8,
          between30and45min: 3,
          above45min: 11,
          inService: 27,
          waiting: 22,
        },
        {
          id: "1-1",
          name: "SMADS",
          parentId: "1",
          isMainUnit: false,
          services: 17,
          waitTime: "01:52:45",
          under30min: 4,
          between30and45min: 3,
          above45min: 11,
          inService: 4,
          waiting: 18,
        },
        {
          id: "1-2",
          name: "ENEL",
          parentId: "1",
          isMainUnit: false,
          services: 9,
          waitTime: "00:16:41",
          under30min: 3,
          between30and45min: 0,
          above45min: 0,
          inService: 1,
          waiting: 3,
        },
        {
          id: "1-3",
          name: "DESCOMPLICAR DIGITAL",
          parentId: "1",
          isMainUnit: false,
          services: 65,
          waitTime: "00:03:08",
          under30min: 1,
          between30and45min: 0,
          above45min: 0,
          inService: 6,
          waiting: 1,
        },
        {
          id: "1-4",
          name: "BANCO DO BRASIL",
          parentId: "1",
          isMainUnit: false,
          services: 0,
          waitTime: "00:00:00",
          under30min: 0,
          between30and45min: 0,
          above45min: 0,
          inService: 0,
          waiting: 0,
        },
        {
          id: "1-5",
          name: "DIREITOS HUMANOS",
          parentId: "1",
          isMainUnit: false,
          services: 8,
          waitTime: "00:00:00",
          under30min: 0,
          between30and45min: 0,
          above45min: 0,
          inService: 0,
          waiting: 0,
        },
        {
          id: "2",
          name: "DESCOMPLICAR SANTO AMARO",
          isMainUnit: true,
          totalServices: "277",
          services: 277,
          waitTime: "01:36:07",
          under30min: 22,
          between30and45min: 3,
          above45min: 10,
          inService: 13,
          waiting: 35,
        },
        {
          id: "3",
          name: "DESCOMPLICAR PENHA",
          isMainUnit: true,
          totalServices: "266",
          services: 266,
          waitTime: "01:31:46",
          under30min: 17,
          between30and45min: 3,
          above45min: 1,
          inService: 29,
          waiting: 21,
        },
        {
          id: "4",
          name: "DESCOMPLICAR IPIRANGA",
          isMainUnit: true,
          totalServices: "100",
          services: 100,
          waitTime: "01:12:53",
          under30min: 5,
          between30and45min: 4,
          above45min: 10,
          inService: 15,
          waiting: 19,
        },
        {
          id: "5",
          name: "DESCOMPLICAR SANTANA - TUCURUVI",
          isMainUnit: true,
          totalServices: "156",
          services: 156,
          waitTime: "01:12:52",
          under30min: 7,
          between30and45min: 2,
          above45min: 6,
          inService: 12,
          waiting: 15,
        },
      ])
    }, 500) // Simulate network delay
  })
}
